name: Credarp
URL: http://credarp.com
description: "credarp"
tagline: " We build web and native mobile app at Credarp. Our product is elbum.in, an analytic tool for sport teams to track, collect and organize their statistics. We also develop Ruby on Rails and iOS projects. This company was been estalblished by Roy, Brian and Labrada in July 2013."
teamtitle: "WE MAKE AWESOME STUFF !"

members:
  - title: "Brian | Developer"
    image: "web_head_brian.png"
    bio: "Brian is a software engineer who wants to make the world better by his code. He likes baseball, reading novels, and doing tai chi."
    links:
      - title: "Blog"
        url: "http://brian.logdown.com/"
        class: "fa-pencil"
      - title: "Github"
        url: "https://github.com/brianhu"
        class: "fa-github"
      - title: "Twitter"
        url: "https://twitter.com/BM_Hu"
        class: "fa-twitter"
      - title: "Facebook"
        url: "https://www.facebook.com/chihwei.hu1"
        class: "fa-facebook"
  - title: "Labrada | Designer"
    image: "web_head_labrada.png"
    bio: "Labrada is major in industrial design and now working on product, graphic, media and UI design. His favorite food is dumpling bun and soy milk. He eat EVERYDAY."
    links:
      - title: "Facebook"
        url: "https://www.facebook.com/labrada.chang"
        class: "fa-facebook"
      - title: "Twitter"
        url: "http://twitter.com/labradachang"
        class: "fa-twitter"
  - title: "Roy | Product Manager"
    image: "web_head_roy.png"
    bio: "Roy is a dreamer, singer and basketball player, loving jogging, reading and cooking. He is also the the founder of Dreamers' Day, which is the biggest student startup community in Taiwan. "
    links:
      - title: "Blog"
        url: "http://about.roykung.com/"
        class: "fa-pencil"
      - title: "Github"
        url: "http://http://github.com/roykunglin"
        class: "fa-github"
      - title: "Twitter"
        url: "http://twitter.com/roylinkung"
        class: "fa-twitter"
      - title: "Facebook"
        url: "http://facebook.com/roylinkung"
        class: "fa-facebook"
  - title: "Gary | Developer"
    image: "web_head_gary.png"
    bio: "Started working with ruby on rails in late 2011 and since then I worked on a wide variety of projects and website. I am the web developer of Credarp to boost its product development."
    links:
      - title: "Blog"
        url: "http://about.garylai.ch"
        class: "fa-pencil"
      - title: "Github"
        url: "http://github.com/garylai1990"
        class: "fa-github"
      - title: "Twitter"
        url: "http://github.com/garylai1990"
        class: "fa-twitter"
      - title: "Facebook"
        url: "https://www.facebook.com/GaryLai.CH"
        class: "fa-facebook"
  - title: "Boyo | Developer"
    image: "web_head-boyo.png"
    bio: "Boyo Chen is a 19-year old boy. He is also a member of NTU baseball team. Having strong interest in programming, he wishes to do more and learn more so as to get ready of devoting himself to the computer science world."
    links:
      - title: "Facebook"
        url: "https://www.facebook.com/profile.php?id=100001421548102"
        class: "fa-facebook"

## settings

permalink: /blog/:year/:month/:day/:title/
paginate: 10
pygments: true
markdown: redcarpet
exclude: [".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor,CNAME"]
