name: Credarp
URL: http://credarp.com
description: "credarp"
tagline: " We make web and native mobile app at Credarp. Our product is elbum.in, an analytic tool for sport teams to track, collect and organize their statistics. We also develop Ruby on Rails and iOS projects. This company was been estalblished by Roy, Brian and Labrada in July 2013."
teamtitle: "WE MAKE AWESOME STUFF !"

members:
  - title: "Brian | Developer"
    image: "web_head_brian.png"
    bio: "I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan.I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan."
    links:
      - title: "Blog"
        url: "http://brian.logdown.com/"
        class: "fa-pencil"
      - title: "Github"
        url: "https://github.com/brianhu"
        class: "fa-github"
      - title: "Twitter"
        url: "https://twitter.com/followers"
        class: "fa-twitter"
      - title: "Facebook"
        url: "https://www.facebook.com/chihwei.hu1"
        class: "fa-facebook"
  - title: "Labrada| Designer"
    image: "web_head_labrada.png"
    bio: "I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan.I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan."
    links:
      - title: "Facebook"
        url: "http://brian.logdown.com/"
        class: "fa-facebook"
      - title: "Twitter"
        url: "http://twitter.com/labradachang"
        class: "fa-twitter"
  - title: "Roy | Product Manager"
    image: "web_head_roy.png"
    bio: "I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan.I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan."
    links:
      - title: "Blog"
        url: "http://roykung.com/"
        class: "fa-pencil"
      - title: "Github"
        url: "http://http://github/roykunglin"
        class: "fa-github"
      - title: "Twitter"
        url: "http://twitter.com/roylinkung"
        class: "fa-twitter"
      - title: "Facebook"
        url: "http://facebook"
        class: "fa-facebook"
  - title: "Gary | Developer"
    image: "web_head_gary.png"
    bio: "I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan.I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan."
    links:
      - title: "Blog"
        url: "http://garylai.ch"
        class: "fa-pencil"
      - title: "Github"
        url: "http://github.com/garylai1990"
        class: "fa-github"
      - title: "Twitter"
        url: "http://github.com/garylai1990"
        class: "fa-twitter"
      - title: "Facebook"
        url: "https://www.facebook.com/GaryLai.CH"
        class: "fa-facebook"
  - title: "Boyo | Developer"
    image: "web_head-boyo.png"
    bio: "I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan.I'm a dreamer, singer and basketball player, loving jogging, reading and cooking, and now running a startup in Taipei, Taiwan."
    links:
      - title: "Facebook"
        url: "https://www.facebook.com/profile.php?id=100001421548102"
        class: "fa-facebook"

## settings

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true
markdown: redcarpet
exclude: [".gitignore", "README.md", "Rakefile", "changelog.md", "Gemfile", "Gemfile.lock", "Procfile", "vendor"]
